<?php


namespace AppBundle\Repository;


use Doctrine\ORM\EntityRepository;

class DinosaurRepository extends EntityRepository
{
    public function findAll()
    {
        return parent::findAll(); // TODO: Change the autogenerated stub
    }
}
